channels:
- conda-forge
dependencies:
- python=3.13.1
- pip<=24.3.1
- pip:
  - mlflow==2.20.2
  - cloudpickle==3.1.1
  - numpy==2.2.3
  - pandas==2.2.3
  - psutil==7.0.0
  - scikit-learn==1.6.1
  - scipy==1.15.2
  - xgboost==2.1.4
name: mlflow-env
